import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { OfficeWhereUniqueInput } from "../office/OfficeWhereUniqueInput";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { PropertyWhereUniqueInput } from "../property/PropertyWhereUniqueInput";
import { ReportListRelationFilter } from "../report/ReportListRelationFilter";
import { RequestListRelationFilter } from "../request/RequestListRelationFilter";
import { ServiceListRelationFilter } from "../service/ServiceListRelationFilter";
import { TransactionListRelationFilter } from "../transaction/TransactionListRelationFilter";

export type BookingWhereInput = {
  additionalInformation?: StringNullableFilter;
  additionalServices?: JsonFilter;
  bookingNotes?: StringNullableFilter;
  bookingPrice?: FloatNullableFilter;
  bookingSource?: "Option1";
  bookingStatus?: "Option1";
  checkInDatetime?: DateTimeNullableFilter;
  checkOutDatetime?: DateTimeNullableFilter;
  client?: StringNullableFilter;
  id?: StringFilter;
  numberOfGuests?: IntNullableFilter;
  office?: OfficeWhereUniqueInput;
  platformBookingId?: StringNullableFilter;
  platformCommissions?: FloatNullableFilter;
  platformSource?: StringNullableFilter;
  principalService?: StringNullableFilter;
  productsReposition?: BooleanNullableFilter;
  property?: PropertyWhereUniqueInput;
  reports?: ReportListRelationFilter;
  requests?: RequestListRelationFilter;
  services?: ServiceListRelationFilter;
  synchronizationStatus?: "Option1";
  transactions?: TransactionListRelationFilter;
};
