/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingUpdateManyWithoutOfficesInput } from "./BookingUpdateManyWithoutOfficesInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ReportUpdateManyWithoutOfficesInput } from "./ReportUpdateManyWithoutOfficesInput";
import { RequestUpdateManyWithoutOfficesInput } from "./RequestUpdateManyWithoutOfficesInput";
import { ServiceUpdateManyWithoutOfficesInput } from "./ServiceUpdateManyWithoutOfficesInput";
import { EnumOfficeStatus } from "./EnumOfficeStatus";

@InputType()
class OfficeUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BookingUpdateManyWithoutOfficesInput,
  })
  @ValidateNested()
  @Type(() => BookingUpdateManyWithoutOfficesInput)
  @IsOptional()
  @Field(() => BookingUpdateManyWithoutOfficesInput, {
    nullable: true,
  })
  bookings?: BookingUpdateManyWithoutOfficesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  contactInformation?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currentBookings?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  franchisee?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  maxBookingCapacity?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  operatingHours?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  operationManagersIds?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutOfficesInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutOfficesInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutOfficesInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutOfficesInput;

  @ApiProperty({
    required: false,
    type: () => RequestUpdateManyWithoutOfficesInput,
  })
  @ValidateNested()
  @Type(() => RequestUpdateManyWithoutOfficesInput)
  @IsOptional()
  @Field(() => RequestUpdateManyWithoutOfficesInput, {
    nullable: true,
  })
  requests?: RequestUpdateManyWithoutOfficesInput;

  @ApiProperty({
    required: false,
    type: () => ServiceUpdateManyWithoutOfficesInput,
  })
  @ValidateNested()
  @Type(() => ServiceUpdateManyWithoutOfficesInput)
  @IsOptional()
  @Field(() => ServiceUpdateManyWithoutOfficesInput, {
    nullable: true,
  })
  services?: ServiceUpdateManyWithoutOfficesInput;

  @ApiProperty({
    required: false,
    enum: EnumOfficeStatus,
  })
  @IsEnum(EnumOfficeStatus)
  @IsOptional()
  @Field(() => EnumOfficeStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  teamIds?: InputJsonValue;
}

export { OfficeUpdateInput as OfficeUpdateInput };
