/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsEnum,
  IsDate,
  IsInt,
  ValidateNested,
  IsBoolean,
} from "class-validator";

import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumBookingBookingSource } from "./EnumBookingBookingSource";
import { EnumBookingBookingStatus } from "./EnumBookingBookingStatus";
import { Type } from "class-transformer";
import { OfficeWhereUniqueInput } from "../../office/base/OfficeWhereUniqueInput";
import { PropertyWhereUniqueInput } from "../../property/base/PropertyWhereUniqueInput";
import { ReportUpdateManyWithoutBookingsInput } from "./ReportUpdateManyWithoutBookingsInput";
import { RequestUpdateManyWithoutBookingsInput } from "./RequestUpdateManyWithoutBookingsInput";
import { ServiceUpdateManyWithoutBookingsInput } from "./ServiceUpdateManyWithoutBookingsInput";
import { EnumBookingSynchronizationStatus } from "./EnumBookingSynchronizationStatus";
import { TransactionUpdateManyWithoutBookingsInput } from "./TransactionUpdateManyWithoutBookingsInput";

@InputType()
class BookingUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  additionalInformation?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  additionalServices?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bookingNotes?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  bookingPrice?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumBookingBookingSource,
  })
  @IsEnum(EnumBookingBookingSource)
  @IsOptional()
  @Field(() => EnumBookingBookingSource, {
    nullable: true,
  })
  bookingSource?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumBookingBookingStatus,
  })
  @IsEnum(EnumBookingBookingStatus)
  @IsOptional()
  @Field(() => EnumBookingBookingStatus, {
    nullable: true,
  })
  bookingStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  checkInDatetime?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  checkOutDatetime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  client?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfGuests?: number | null;

  @ApiProperty({
    required: false,
    type: () => OfficeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OfficeWhereUniqueInput)
  @IsOptional()
  @Field(() => OfficeWhereUniqueInput, {
    nullable: true,
  })
  office?: OfficeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  platformBookingId?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  platformCommissions?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  platformSource?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  principalService?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  productsReposition?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => PropertyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PropertyWhereUniqueInput)
  @IsOptional()
  @Field(() => PropertyWhereUniqueInput, {
    nullable: true,
  })
  property?: PropertyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutBookingsInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutBookingsInput;

  @ApiProperty({
    required: false,
    type: () => RequestUpdateManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => RequestUpdateManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => RequestUpdateManyWithoutBookingsInput, {
    nullable: true,
  })
  requests?: RequestUpdateManyWithoutBookingsInput;

  @ApiProperty({
    required: false,
    type: () => ServiceUpdateManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => ServiceUpdateManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => ServiceUpdateManyWithoutBookingsInput, {
    nullable: true,
  })
  services?: ServiceUpdateManyWithoutBookingsInput;

  @ApiProperty({
    required: false,
    enum: EnumBookingSynchronizationStatus,
  })
  @IsEnum(EnumBookingSynchronizationStatus)
  @IsOptional()
  @Field(() => EnumBookingSynchronizationStatus, {
    nullable: true,
  })
  synchronizationStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutBookingsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutBookingsInput;
}

export { BookingUpdateInput as BookingUpdateInput };
