/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ServiceTypeService } from "../serviceType.service";
import { ServiceTypeCreateInput } from "./ServiceTypeCreateInput";
import { ServiceType } from "./ServiceType";
import { Request } from "../../request/base/Request";
import { ServiceTypeFindManyArgs } from "./ServiceTypeFindManyArgs";
import { ServiceTypeWhereUniqueInput } from "./ServiceTypeWhereUniqueInput";
import { ServiceTypeUpdateInput } from "./ServiceTypeUpdateInput";
import { ServiceFindManyArgs } from "../../service/base/ServiceFindManyArgs";
import { Service } from "../../service/base/Service";
import { ServiceWhereUniqueInput } from "../../service/base/ServiceWhereUniqueInput";

export class ServiceTypeControllerBase {
  constructor(protected readonly service: ServiceTypeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceType })
  async createServiceType(
    @common.Body() data: ServiceTypeCreateInput
  ): Promise<ServiceType> {
    return await this.service.createServiceType({
      data: data,
      select: {
        additionalServices: true,
        createdAt: true,
        description: true,
        id: true,
        isPrincipal: true,
        name: true,
        numberOfBathrooms: true,
        numberOfBedrooms: true,
        photos: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceType] })
  @ApiNestedQuery(ServiceTypeFindManyArgs)
  async serviceTypes(@common.Req() request: Request): Promise<ServiceType[]> {
    const args = plainToClass(ServiceTypeFindManyArgs, request.query);
    return this.service.serviceTypes({
      ...args,
      select: {
        additionalServices: true,
        createdAt: true,
        description: true,
        id: true,
        isPrincipal: true,
        name: true,
        numberOfBathrooms: true,
        numberOfBedrooms: true,
        photos: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async serviceType(
    @common.Param() params: ServiceTypeWhereUniqueInput
  ): Promise<ServiceType | null> {
    const result = await this.service.serviceType({
      where: params,
      select: {
        additionalServices: true,
        createdAt: true,
        description: true,
        id: true,
        isPrincipal: true,
        name: true,
        numberOfBathrooms: true,
        numberOfBedrooms: true,
        photos: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateServiceType(
    @common.Param() params: ServiceTypeWhereUniqueInput,
    @common.Body() data: ServiceTypeUpdateInput
  ): Promise<ServiceType | null> {
    try {
      return await this.service.updateServiceType({
        where: params,
        data: data,
        select: {
          additionalServices: true,
          createdAt: true,
          description: true,
          id: true,
          isPrincipal: true,
          name: true,
          numberOfBathrooms: true,
          numberOfBedrooms: true,
          photos: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteServiceType(
    @common.Param() params: ServiceTypeWhereUniqueInput
  ): Promise<ServiceType | null> {
    try {
      return await this.service.deleteServiceType({
        where: params,
        select: {
          additionalServices: true,
          createdAt: true,
          description: true,
          id: true,
          isPrincipal: true,
          name: true,
          numberOfBathrooms: true,
          numberOfBedrooms: true,
          photos: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/services")
  @ApiNestedQuery(ServiceFindManyArgs)
  async findServices(
    @common.Req() request: Request,
    @common.Param() params: ServiceTypeWhereUniqueInput
  ): Promise<Service[]> {
    const query = plainToClass(ServiceFindManyArgs, request.query);
    const results = await this.service.findServices(params.id, {
      ...query,
      select: {
        basePrice: true,

        booking: {
          select: {
            id: true,
          },
        },

        category: true,
        createdAt: true,
        description: true,
        equipmentRequirements: true,
        estimatedDuration: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        operators: true,

        property: {
          select: {
            id: true,
          },
        },

        serviceType: {
          select: {
            id: true,
          },
        },

        specialInstructions: true,
        status: true,
        supervisor: true,
        taskForm: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/services")
  async connectServices(
    @common.Param() params: ServiceTypeWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        connect: body,
      },
    };
    await this.service.updateServiceType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/services")
  async updateServices(
    @common.Param() params: ServiceTypeWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        set: body,
      },
    };
    await this.service.updateServiceType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/services")
  async disconnectServices(
    @common.Param() params: ServiceTypeWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        disconnect: body,
      },
    };
    await this.service.updateServiceType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
